---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - aws_vars.yml
   
  tasks:
    - name: Provision an EC2 instance
      ec2:
         region: eu-west-1
         key_name: "{{ key }}"
         instance_type: t2.micro
         image: "{{ image }}"
         wait: true
         vpc_subnet_id: "{{ subnet }}"
         exact_count: 3
         count_tag:
           Name: DWP-Demo
         assign_public_ip: yes
         instance_tags:
            Name: DWP-Demo
      register: ec2
