---
- hosts: localhost
  connection: local
  gather_facts: False
   
  tasks:
    - name: Provision an EC2 instance
      ec2:
         region: eu-west-1
         key_name: laptop
         instance_type: t2.micro
         image: ami-08f4717d06813bf00
         wait: true
         vpc_subnet_id: subnet-060156ab472724b0b
         instance_tags:
            Name: DWP-Demo
      register: ec2

    - name: install Apache WebServer
      yum:
        name: httpd
        state: latest
      become: yes
    
    - name: Ensure httpd service is started
      service:
        name: httpd
        state: started
      become: yes