---

- name: delete elb classic
  elb_classic_lb:
    name: "ansible-demo"
    state: absent
    region: "{{ ec2_region }}"
    
- name: Get the VPC ID for my network
  ec2_vpc_net_facts:
    region: "{{ ec2_region }}"
  register: vpc_net_facts
  
- name: use set fact for easier variables
  set_fact:
    ec2_vpc_id: "{{vpc_net_facts.vpcs[0].id}}"

- name: Deleted EC2 security group for VPC
  ec2_group:
    name: "{{security_group}}"
    region: "{{ ec2_region }}"
    vpc_id: "{{ec2_vpc_id}}"
    state: absent
  register: delete_sg
  until: delete_sg is not failed
  retries: 50
  when: vpc_net_facts.vpcs|length > 0
  
- name: Delete subnet
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    vpc_id: "{{ec2_vpc_id}}"
    cidr: "{{vpc_cidr}}"
    state: absent
  when: vpc_net_facts.vpcs|length > 0
    
- name: delete the VPC
  ec2_vpc_net:   
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
