---

- name: gather vpc info
  ec2_vpc_net_facts:
    register: vpc

- name: delete gateway
  ec2_vpc_igw:
    state: absent
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ ec2_region }}"

- name: delete route table
  ec2_vpc_route_table:
    state: absent
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ ec2_region }}"

- name: delete subnet
  ec2_vpc_subnet:
    state: absent
    cidr: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"

- name: delete the VPC
  ec2_vpc_net:   
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
