---

- name: create demo vpc
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
  register: vpc

- name: create subnet
  ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"

- name: pass fact when running in tower
  set_stats:
    data:
      subnet: "{{ subnet }}"

- name: create internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: absent
    region: "{{ ec2_region }}"
  register: igw

- name: get route table id
  ec2_vpc_route_table_facts:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc.vpc.id }}"
    state: absent

- name: set up route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    route_table_id: "{{ route_table.route_tables[0].id }}"
    state: absent

- name: create security group
  ec2_group:
    name: "{{ security_group }}"
    description: Ansible demo group
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    state: absent


- name: create elb classic
  elb_classic_lb:
    name: "ansible-demo"
    state: absent
    region: "{{ ec2_region }}"

