---

- name: delete elb classic
  elb_classic_lb:
    name: "ansible-demo"
    state: absent
    region: "{{ ec2_region }}"

- name: delete the subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    cidr: "{{ vpc_cidr }}"
    state: absent
  register: delete_subnet
  until: delete_subnet is not failed
  retries: 5
  delay: 10
    
- name: delete the VPC
  ec2_vpc_net:   
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
