---

- name: delete elb classic
  elb_classic_lb:
    name: "ansible-demo"
    state: absent
    region: "{{ ec2_region }}"

- name: delete the subnet
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    cidr: "{{ vpc_cidr }}"
    state: absent
    
- name: delete the VPC
  ec2_vpc_net:   
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
