---

- name: delete the VPC
  ec2_vpc_net:   
    name: "{{ ansible-demo }}""
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
    purge_cidrs: yes
    register: vpc_delete
