---

- name: delete elb classic
  elb_classic_lb:
    name: "ansible-demo"
    state: absent
    region: "{{ ec2_region }}"

<<<<<<< HEAD
=======
- name: delete the subnet
  ec2_vpc_subnet:
    cidr: "{{ vpc_cidr }}"
    state: absent

>>>>>>> parent of a2d4e4b... going to include it in workflow - dependencies for vpc facts
- name: delete the VPC
  ec2_vpc_net:   
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
