---
- name: launch ec2 instances
  ec2_instance:
    name: "ansible-{{ os }}"
    key_name: "{{ keypair }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_type: "{{ instance_size }}"
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami_id }}"
    user_data: "{{ lookup('file', '{{ os }}-userdata') }}"
    region: "{{ ec2_region }}"
  register: ec2_instance
